quarkus.http.port=28000
quarkus.package.jar.type=uber-jar
quarkus.package.jar.add-runner-suffix=false

# Include custom classpath resources in native image
quarkus.native.resources.includes=ai-workspace-default.yaml
