package com.scivicslab.lxdpups.kafka;

import io.quarkus.runtime.ShutdownEvent;
import io.quarkus.runtime.StartupEvent;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Observes;
import org.eclipse.microprofile.config.inject.ConfigProperty;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.logging.Logger;

/**
 * Manages the Kafka broker lifecycle alongside lxd-pups.
 * <p>
 * On startup, checks if Kafka is reachable at the configured bootstrap server.
 * If not, attempts to locate a local Kafka installation and start it in KRaft mode
 * (no ZooKeeper required). On shutdown, stops Kafka if this manager started it.
 * </p>
 *
 * <p>Kafka search order:
 * <ol>
 *   <li>{@code lxd.pups.kafka.home} config property (if set)</li>
 *   <li>{@code ~/kafka/}</li>
 *   <li>{@code ~/bin/kafka/}</li>
 *   <li>{@code /opt/kafka/}</li>
 * </ol>
 * </p>
 *
 * <p>KRaft data directory: {@code ~/.lxd-pups/kafka-data/}</p>
 */
@ApplicationScoped
public class KafkaLifecycleManager {

    private static final Logger LOG = Logger.getLogger(KafkaLifecycleManager.class.getName());

    private static final List<String> KAFKA_SEARCH_PATHS = List.of(
            System.getProperty("user.home") + "/kafka",
            System.getProperty("user.home") + "/bin/kafka",
            "/opt/kafka"
    );

    private static final String KRAFT_DATA_DIR =
            System.getProperty("user.home") + "/.lxd-pups/kafka-data";

    @ConfigProperty(name = "lxd.pups.kafka.home")
    java.util.Optional<String> kafkaHomeConfig;

    @ConfigProperty(name = "kafka.bootstrap.servers", defaultValue = "localhost:9092")
    String bootstrapServers;

    @ConfigProperty(name = "lxd.pups.kafka.auto-start", defaultValue = "false")
    boolean autoStart;

    private volatile Process kafkaProcess = null;

    void onStart(@Observes StartupEvent ev) {
        // Always write the KRaft setup script so the post-install-cmd in portal.yaml can call it
        // even when ~/kafka/ is not yet present (i.e. will be downloaded on first Start).
        try {
            writeSetupScript();
        } catch (Exception e) {
            LOG.warning("Failed to write Kafka setup script: " + e.getMessage());
        }

        // If ~/kafka/ is already present, run KRaft setup immediately
        var kafkaHome = findKafkaHome();
        if (kafkaHome != null) {
            try {
                ensureKraftStorage(kafkaHome);
            } catch (Exception e) {
                LOG.warning("Kafka KRaft setup failed: " + e.getMessage());
            }

            if (autoStart && !isKafkaReachable()) {
                LOG.info("Auto-starting Kafka from " + kafkaHome);
                startKafka(kafkaHome);
            }
        } else {
            LOG.info("Kafka not found — will be downloaded on first Start button press.");
        }
    }

    void onStop(@Observes ShutdownEvent ev) {
        if (kafkaProcess != null && kafkaProcess.isAlive()) {
            LOG.info("Stopping Kafka...");
            kafkaProcess.destroy();
            try {
                kafkaProcess.waitFor();
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                kafkaProcess.destroyForcibly();
            }
            LOG.info("Kafka stopped");
        }
    }

    // ── private ──

    private boolean isKafkaReachable() {
        var parts = bootstrapServers.split(":");
        var host = parts[0];
        var port = parts.length > 1 ? Integer.parseInt(parts[1]) : 9092;
        try (var s = new Socket()) {
            s.connect(new InetSocketAddress(host, port), 2000);
            return true;
        } catch (IOException e) {
            return false;
        }
    }

    private String findKafkaHome() {
        var configured = kafkaHomeConfig.orElse("").trim();
        if (!configured.isBlank()) {
            var p = Path.of(configured);
            if (Files.isDirectory(p)) return configured;
            LOG.warning("Configured lxd.pups.kafka.home not found: " + configured);
        }
        for (var candidate : KAFKA_SEARCH_PATHS) {
            if (Files.isDirectory(Path.of(candidate))) {
                return candidate;
            }
        }
        return null;
    }

    /**
     * Write an idempotent KRaft setup script to ~/.lxd-pups/kafka-setup.sh.
     * The script is referenced by portal.yaml kafka binary.post-install-cmd,
     * so it runs automatically after Kafka is downloaded and extracted.
     */
    private void writeSetupScript() throws Exception {
        var dataDir = Path.of(KRAFT_DATA_DIR);
        Files.createDirectories(dataDir);
        var scriptFile = dataDir.resolve("kafka-setup.sh");
        var script = """
                #!/bin/bash
                # Auto-generated by KafkaLifecycleManager — do not edit manually.
                # Sets up KRaft (ZooKeeper-free) storage for Kafka.
                set -e
                KAFKA_HOME=~/kafka
                DATA_DIR=%s
                CONFIG=$DATA_DIR/server.properties

                mkdir -p "$DATA_DIR"

                if [ ! -f "$CONFIG" ]; then
                cat > "$CONFIG" << 'KAFKAEOF'
                process.roles=broker,controller
                node.id=1
                controller.quorum.voters=1@localhost:9093
                listeners=PLAINTEXT://:9092,CONTROLLER://:9093
                advertised.listeners=PLAINTEXT://localhost:9092
                controller.listener.names=CONTROLLER
                inter.broker.listener.name=PLAINTEXT
                log.dirs=%s
                num.partitions=1
                offsets.topic.replication.factor=1
                transaction.state.log.replication.factor=1
                transaction.state.log.min.isr=1
                KAFKAEOF
                echo "Wrote KRaft config to $CONFIG"
                fi

                if [ ! -f "$DATA_DIR/meta.properties" ]; then
                UUID=$("$KAFKA_HOME/bin/kafka-storage.sh" random-uuid)
                "$KAFKA_HOME/bin/kafka-storage.sh" format -t "$UUID" -c "$CONFIG"
                echo "KRaft storage formatted with cluster ID $UUID"
                fi

                echo "Kafka KRaft setup complete."
                """.formatted(KRAFT_DATA_DIR, KRAFT_DATA_DIR);
        Files.writeString(scriptFile, script);
        scriptFile.toFile().setExecutable(true);
        LOG.info("Wrote Kafka setup script to " + scriptFile);
    }

    /**
     * Ensure KRaft config and storage are ready.
     * Called on startup so the management UI Start button can immediately launch Kafka.
     */
    private void ensureKraftStorage(String kafkaHome) throws Exception {
        var dataDir = Path.of(KRAFT_DATA_DIR);
        var configFile = dataDir.resolve("server.properties");
        var metaFile = dataDir.resolve("meta.properties");

        Files.createDirectories(dataDir);

        if (!Files.exists(configFile)) {
            writeKraftConfig(configFile, dataDir.toString());
            LOG.info("Wrote KRaft config to " + configFile);
        }

        if (!Files.exists(metaFile)) {
            formatKraftStorage(kafkaHome, configFile.toString());
            LOG.info("KRaft storage formatted at " + dataDir);
        }

        LOG.info("Kafka KRaft storage ready at " + dataDir);
    }

    private void startKafka(String kafkaHome) {
        var configFile = Path.of(KRAFT_DATA_DIR, "server.properties");
        try {
            var startScript = kafkaHome + "/bin/kafka-server-start.sh";
            kafkaProcess = new ProcessBuilder(startScript, configFile.toString())
                    .redirectOutput(ProcessBuilder.Redirect.DISCARD)
                    .redirectError(ProcessBuilder.Redirect.DISCARD)
                    .start();

            Thread.sleep(3000);
            if (!kafkaProcess.isAlive()) {
                LOG.severe("Kafka process exited immediately after start");
                kafkaProcess = null;
                return;
            }

            LOG.info("Kafka started (pid=" + kafkaProcess.pid() + ")");

        } catch (Exception e) {
            LOG.severe("Failed to start Kafka: " + e.getMessage());
            kafkaProcess = null;
        }
    }

    private void writeKraftConfig(Path configFile, String dataDir) throws IOException {
        var config = """
                process.roles=broker,controller
                node.id=1
                controller.quorum.voters=1@localhost:9093
                listeners=PLAINTEXT://:9092,CONTROLLER://:9093
                advertised.listeners=PLAINTEXT://localhost:9092
                controller.listener.names=CONTROLLER
                inter.broker.listener.name=PLAINTEXT
                log.dirs=%s
                num.partitions=1
                offsets.topic.replication.factor=1
                transaction.state.log.replication.factor=1
                transaction.state.log.min.isr=1
                """.formatted(dataDir);
        Files.writeString(configFile, config);
        LOG.info("Wrote KRaft config to " + configFile);
    }

    private void formatKraftStorage(String kafkaHome, String configFile) throws IOException, InterruptedException {
        // Generate a random cluster UUID
        var uuidResult = new ProcessBuilder(
                kafkaHome + "/bin/kafka-storage.sh", "random-uuid")
                .redirectErrorStream(true)
                .start();
        var uuid = new String(uuidResult.getInputStream().readAllBytes()).strip();
        uuidResult.waitFor();

        if (uuid.isBlank()) {
            throw new IOException("Failed to generate Kafka cluster UUID");
        }

        var format = new ProcessBuilder(
                kafkaHome + "/bin/kafka-storage.sh", "format",
                "-t", uuid, "-c", configFile)
                .redirectErrorStream(true)
                .start();
        var output = new String(format.getInputStream().readAllBytes());
        int exitCode = format.waitFor();
        if (exitCode != 0) {
            throw new IOException("kafka-storage.sh format failed (exit=" + exitCode + "): " + output);
        }
        LOG.info("KRaft storage formatted with cluster ID " + uuid);
    }
}
